# Define column mappings for consistent column naming across dataframes
column_mapping_agents = {
    "email": "email",
    "full_name": "full_name",
    "first_name": "first_name",
    "middle_name": "middle_name",
    "last_name": "last_name",
    "suffix": "suffix",
    "office_name": "office_name",
    "office_address_1": "office_address",
    "office_address_2": "office_address_2",
    "office_city": "office_city",
    "office_state": "office_state",
    "office_zip": "office_zip",
    "office_county": "office_county",
    "office_phone": "office_phone",
    "office_fax": "office_fax",
    "cell_phone": "cell_phone",
    "license_type": "license_type",
    "license_number": "license_number",
    "license_issued_at": "license_issued_at",
    "license_expires_at": "license_expires_at",
    "association": "association",
    "id": "agent_id",
    "uuid": "uuid",
}

column_mapping_agents_2 = {
    "agentdetails__email": "email",
    "agentdetails__phone": "agent_phone",
    "agentdetails__mlsdetails__shortname": "mls_shortname",
    "agentdetails__mlsdetails__longname": "mls_longname",
    "agentdetails__mlsdetails__state": "mls_state",
    "agentdetails__office__name": "office_name",
    "agentdetails__cellphone": "cell_phone",
    "agentdetails__firstname": "first_name",
    "agentdetails__middlename": "middle_name",
    "agentdetails__lastname": "last_name",
    "agentdetails__agentdisplayname": "screen_name",
    "agentdetails__license": "license_number",
    "agentdetails__office__mlsofficeid": "office_id",
    "agentdetails__office__subhead": "office_subhead",
    "agentdetails__office__fullstreetaddress": "office_address",
    "agentdetails__office__city": "office_city",
    "agentdetails__office__state": "office_state",
    "agentdetails__office__zip": "office_zip",
    "agentdetails__office__email": "office_email",
    "agentdetails__office__phone": "office_phone",
    "agentdetails__office__fax": "office_fax",
    "agentdetails__mlsagentfullname": "full_name",
    "agentdetails__displayaddress__fullstreetaddress": "display_address",
    "agentdetails__displayaddress__city": "display_city",
    "agentdetails__displayaddress__state": "display_state",
    "agentdetails__displayaddress__zip": "display_zip",
    "agentdetails__mlsid": "mls_id",
    "agentdetails__mls": "mls",
}

column_mapping_all_agents = {
    "ID": "agent_id",
    "Name": "full_name",
    "Title": "title",
    "isPremierAgent": "is_premier_agent",
    "Reviews": "reviews",
    "Rating": "rating",
    "Team": "team_name",
    "Team_encodedZuid": "team_encoded_zuid",
    "Team_role": "team_role",
    "Team_URL": "team_url",
    "Org": "office_name",
    "Street": "office_address",
    "City": "office_city",
    "State": "office_state",
    "Zip": "office_zip",
    "Full_address": "full_address",
    "Office": "office_phone",
    "Phone": "agent_phone",
    "Fax": "office_fax",
    "Cell": "cell_phone",
    "Email": "email",
    "Website": "website",
    "Facebook": "facebook",
    "Linkedin": "linkedin",
    "Licenses": "license_number",
    "Other_Licenses": "other_licenses",
    "Member_since": "member_since",
    "Screenname": "screen_name",
    "sales": "sales",
    "sales_api": "sales_api",
    "sales_lastyear": "sales_last_year",
    "priceRangeThreeYearMin": "price_range_min",
    "priceRangeThreeYearMax": "price_range_max",
    "averageValueThreeYear": "avg_value_three_year",
    "stats_include_team": "stats_include_team",
    "encodedZuid": "encoded_zuid",
    "Team_member_name(cut by ^)": "team_member_names",
    "Team_member_screenname(cut by ^)": "team_member_screennames",
    "Team_member_encodedZuid(cut by ^)": "team_member_encoded_zuid",
    "Lender_name": "lender_name",
    "Date_s": "date_s",
    "Service_areas": "service_areas",
    "PageUrl": "page_url",
}
